name: gubify
description: "A new Flutter project."
publish_to: 'none'

version: 0.8.0+3

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.0.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  intl: ^0.20.2
  app_links: ^7.2.1
  audioplayers: ^6.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/app_icon.png
    - assets/images/auth/auth_entry_background.png
    - assets/images/auth/auth_entry_logo.png
    - assets/illustrations/plant.png
    - assets/illustrations/sofa.png
    - assets/backgrounds/
    - assets/images/
    - assets/images/backgrounds/
    - assets/sounds/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/images/app_icon.png"

  adaptive_icon_background: "#0B1220"
  adaptive_icon_foreground: "assets/images/app_icon.png"

  min_sdk_android: 21
