// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB7vG8ALu0ZAS6ctxLxZJVXxnZqVDPZnE',
    appId: '1:741423330029:web:26524a3736858bb06f52e4',
    messagingSenderId: '741423330029',
    projectId: 'gubify-a3e2c',
    authDomain: 'gubify-a3e2c.firebaseapp.com',
    storageBucket: 'gubify-a3e2c.firebasestorage.app',
    measurementId: 'G-D1MKEE8BYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaruxeV3NfiWO7nU2VcD7rBbhdeZy1GsI',
    appId: '1:741423330029:android:6e76f8c6b8daf1156f52e4',
    messagingSenderId: '741423330029',
    projectId: 'gubify-a3e2c',
    storageBucket: 'gubify-a3e2c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMBNVJCU9ZGcd0h5vCzJmqJI9FgujTdns',
    appId: '1:741423330029:ios:555bd16f1a786e2a6f52e4',
    messagingSenderId: '741423330029',
    projectId: 'gubify-a3e2c',
    storageBucket: 'gubify-a3e2c.firebasestorage.app',
    iosBundleId: 'com.gubify.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMBNVJCU9ZGcd0h5vCzJmqJI9FgujTdns',
    appId: '1:741423330029:ios:555bd16f1a786e2a6f52e4',
    messagingSenderId: '741423330029',
    projectId: 'gubify-a3e2c',
    storageBucket: 'gubify-a3e2c.firebasestorage.app',
    iosBundleId: 'com.gubify.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB7vG8ALu0ZAS6ctxLxZJVXxnZqVDPZnE',
    appId: '1:741423330029:web:42337b15823a61256f52e4',
    messagingSenderId: '741423330029',
    projectId: 'gubify-a3e2c',
    authDomain: 'gubify-a3e2c.firebaseapp.com',
    storageBucket: 'gubify-a3e2c.firebasestorage.app',
    measurementId: 'G-9G8PZQHXEJ',
  );
}
