// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxHneU5B5UTSp9Uhnejjnr8iQefpVFypA',
    appId: '1:57532357766:web:fda5769c80a6be8eafc507',
    messagingSenderId: '57532357766',
    projectId: 'hubfy-34c2e',
    authDomain: 'hubfy-34c2e.firebaseapp.com',
    storageBucket: 'hubfy-34c2e.firebasestorage.app',
    measurementId: 'G-WMZ9CLY2K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG0No3BY78nR-UB_3Td5oR8RyUipp6aeo',
    appId: '1:57532357766:android:2d21d801f66b8fd2afc507',
    messagingSenderId: '57532357766',
    projectId: 'hubfy-34c2e',
    storageBucket: 'hubfy-34c2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9yMNaUDQpjNSMcoO7PiAo1Yo6C9Kn7Mg',
    appId: '1:57532357766:ios:3ff904482452a571afc507',
    messagingSenderId: '57532357766',
    projectId: 'hubfy-34c2e',
    storageBucket: 'hubfy-34c2e.firebasestorage.app',
    iosBundleId: 'com.example.Hubfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9yMNaUDQpjNSMcoO7PiAo1Yo6C9Kn7Mg',
    appId: '1:57532357766:ios:3ff904482452a571afc507',
    messagingSenderId: '57532357766',
    projectId: 'hubfy-34c2e',
    storageBucket: 'hubfy-34c2e.firebasestorage.app',
    iosBundleId: 'com.example.Hubfy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxHneU5B5UTSp9Uhnejjnr8iQefpVFypA',
    appId: '1:57532357766:web:be2f8611b38cc3f0afc507',
    messagingSenderId: '57532357766',
    projectId: 'hubfy-34c2e',
    authDomain: 'hubfy-34c2e.firebaseapp.com',
    storageBucket: 'hubfy-34c2e.firebasestorage.app',
    measurementId: 'G-VDJ3LW4D9Y',
  );
}
